INSERT INTO Pays (libelle_pays) VALUES ('Afghanistan');
INSERT INTO Pays (libelle_pays) VALUES ('Afrique du Sud');
INSERT INTO Pays (libelle_pays) VALUES ('Albanie');
INSERT INTO Pays (libelle_pays) VALUES ('Algérie');
INSERT INTO Pays (libelle_pays) VALUES ('Allemagne');
INSERT INTO Pays (libelle_pays) VALUES ('Andorre');
INSERT INTO Pays (libelle_pays) VALUES ('Angola');
INSERT INTO Pays (libelle_pays) VALUES ('Antigua-et-Barbuda');
INSERT INTO Pays (libelle_pays) VALUES ('Arabie Saoudite');
INSERT INTO Pays (libelle_pays) VALUES ('Argentine');
INSERT INTO Pays (libelle_pays) VALUES ('Arménie');
INSERT INTO Pays (libelle_pays) VALUES ('Australie');
INSERT INTO Pays (libelle_pays) VALUES ('Autriche');
INSERT INTO Pays (libelle_pays) VALUES ('Azerbaïdjan');
INSERT INTO Pays (libelle_pays) VALUES ('Bahamas');
INSERT INTO Pays (libelle_pays) VALUES ('Bahreïn');
INSERT INTO Pays (libelle_pays) VALUES ('Bangladesh');
INSERT INTO Pays (libelle_pays) VALUES ('Barbade');
INSERT INTO Pays (libelle_pays) VALUES ('Belgique');
INSERT INTO Pays (libelle_pays) VALUES ('Belize');
INSERT INTO Pays (libelle_pays) VALUES ('Bénin');
INSERT INTO Pays (libelle_pays) VALUES ('Bhoutan');
INSERT INTO Pays (libelle_pays) VALUES ('Biélorussie');
INSERT INTO Pays (libelle_pays) VALUES ('Birmanie');
INSERT INTO Pays (libelle_pays) VALUES ('Bolivie');
INSERT INTO Pays (libelle_pays) VALUES ('Bosnie-Herzégovine');
INSERT INTO Pays (libelle_pays) VALUES ('Botswana');
INSERT INTO Pays (libelle_pays) VALUES ('Brésil');
INSERT INTO Pays (libelle_pays) VALUES ('Brunei');
INSERT INTO Pays (libelle_pays) VALUES ('Bulgarie');
INSERT INTO Pays (libelle_pays) VALUES ('Burkina Faso');
INSERT INTO Pays (libelle_pays) VALUES ('Burundi');
INSERT INTO Pays (libelle_pays) VALUES ('Cambodge');
INSERT INTO Pays (libelle_pays) VALUES ('Cameroun');
INSERT INTO Pays (libelle_pays) VALUES ('Canada');
INSERT INTO Pays (libelle_pays) VALUES ('Cap-Vert');
INSERT INTO Pays (libelle_pays) VALUES ('Chili');
INSERT INTO Pays (libelle_pays) VALUES ('Chine');
INSERT INTO Pays (libelle_pays) VALUES ('Chypre');
INSERT INTO Pays (libelle_pays) VALUES ('Colombie');
INSERT INTO Pays (libelle_pays) VALUES ('Comores');
INSERT INTO Pays (libelle_pays) VALUES ('Congo');
INSERT INTO Pays (libelle_pays) VALUES ('Corée du Nord');
INSERT INTO Pays (libelle_pays) VALUES ('Corée du Sud');
INSERT INTO Pays (libelle_pays) VALUES ('Costa Rica');
INSERT INTO Pays (libelle_pays) VALUES ('Côte d''Ivoire');
INSERT INTO Pays (libelle_pays) VALUES ('Croatie');
INSERT INTO Pays (libelle_pays) VALUES ('Cuba');
INSERT INTO Pays (libelle_pays) VALUES ('Danemark');
INSERT INTO Pays (libelle_pays) VALUES ('Djibouti');
INSERT INTO Pays (libelle_pays) VALUES ('Dominique');
INSERT INTO Pays (libelle_pays) VALUES ('Égypte');
INSERT INTO Pays (libelle_pays) VALUES ('Émirats arabes unis');
INSERT INTO Pays (libelle_pays) VALUES ('Équateur');
INSERT INTO Pays (libelle_pays) VALUES ('Érythrée');
INSERT INTO Pays (libelle_pays) VALUES ('Espagne');
INSERT INTO Pays (libelle_pays) VALUES ('Estonie');
INSERT INTO Pays (libelle_pays) VALUES ('États-Unis');
INSERT INTO Pays (libelle_pays) VALUES ('Éthiopie');
INSERT INTO Pays (libelle_pays) VALUES ('Fidji');
INSERT INTO Pays (libelle_pays) VALUES ('Finlande');
INSERT INTO Pays (libelle_pays) VALUES ('France');
INSERT INTO Pays (libelle_pays) VALUES ('Gabon');
INSERT INTO Pays (libelle_pays) VALUES ('Gambie');
INSERT INTO Pays (libelle_pays) VALUES ('Géorgie');
INSERT INTO Pays (libelle_pays) VALUES ('Ghana');
INSERT INTO Pays (libelle_pays) VALUES ('Grèce');
INSERT INTO Pays (libelle_pays) VALUES ('Grenade');
INSERT INTO Pays (libelle_pays) VALUES ('Guatemala');
INSERT INTO Pays (libelle_pays) VALUES ('Guinée');
INSERT INTO Pays (libelle_pays) VALUES ('Guinée équatoriale');
INSERT INTO Pays (libelle_pays) VALUES ('Guinée-Bissau');
INSERT INTO Pays (libelle_pays) VALUES ('Guyana');
INSERT INTO Pays (libelle_pays) VALUES ('Haïti');
INSERT INTO Pays (libelle_pays) VALUES ('Honduras');
INSERT INTO Pays (libelle_pays) VALUES ('Hongrie');
INSERT INTO Pays (libelle_pays) VALUES ('Îles Marshall');
INSERT INTO Pays (libelle_pays) VALUES ('Îles Salomon');
INSERT INTO Pays (libelle_pays) VALUES ('Inde');
INSERT INTO Pays (libelle_pays) VALUES ('Indonésie');
INSERT INTO Pays (libelle_pays) VALUES ('Irak');
INSERT INTO Pays (libelle_pays) VALUES ('Iran');
INSERT INTO Pays (libelle_pays) VALUES ('Irlande');
INSERT INTO Pays (libelle_pays) VALUES ('Islande');
INSERT INTO Pays (libelle_pays) VALUES ('Italie');
INSERT INTO Pays (libelle_pays) VALUES ('Jamaïque');
INSERT INTO Pays (libelle_pays) VALUES ('Japon');
INSERT INTO Pays (libelle_pays) VALUES ('Jordanie');
INSERT INTO Pays (libelle_pays) VALUES ('Kazakhstan');
INSERT INTO Pays (libelle_pays) VALUES ('Kenya');
INSERT INTO Pays (libelle_pays) VALUES ('Kirghizistan');
INSERT INTO Pays (libelle_pays) VALUES ('Kiribati');
INSERT INTO Pays (libelle_pays) VALUES ('Koweït');
INSERT INTO Pays (libelle_pays) VALUES ('Laos');
INSERT INTO Pays (libelle_pays) VALUES ('Lesotho');
INSERT INTO Pays (libelle_pays) VALUES ('Lettonie');
INSERT INTO Pays (libelle_pays) VALUES ('Liban');
INSERT INTO Pays (libelle_pays) VALUES ('Liberia');
INSERT INTO Pays (libelle_pays) VALUES ('Libye');
INSERT INTO Pays (libelle_pays) VALUES ('Liechtenstein');
INSERT INTO Pays (libelle_pays) VALUES ('Lituanie');
INSERT INTO Pays (libelle_pays) VALUES ('Luxembourg');
INSERT INTO Pays (libelle_pays) VALUES ('Macédoine du Nord');
INSERT INTO Pays (libelle_pays) VALUES ('Madagascar');
INSERT INTO Pays (libelle_pays) VALUES ('Malaisie');
INSERT INTO Pays (libelle_pays) VALUES ('Malawi');
INSERT INTO Pays (libelle_pays) VALUES ('Maldives');
INSERT INTO Pays (libelle_pays) VALUES ('Mali');
INSERT INTO Pays (libelle_pays) VALUES ('Malte');
INSERT INTO Pays (libelle_pays) VALUES ('Maroc');
INSERT INTO Pays (libelle_pays) VALUES ('Maurice');
INSERT INTO Pays (libelle_pays) VALUES ('Mauritanie');
INSERT INTO Pays (libelle_pays) VALUES ('Mexique');
INSERT INTO Pays (libelle_pays) VALUES ('Micronésie');
INSERT INTO Pays (libelle_pays) VALUES ('Moldavie');
INSERT INTO Pays (libelle_pays) VALUES ('Monaco');
INSERT INTO Pays (libelle_pays) VALUES ('Mongolie');
INSERT INTO Pays (libelle_pays) VALUES ('Monténégro');
INSERT INTO Pays (libelle_pays) VALUES ('Mozambique');
INSERT INTO Pays (libelle_pays) VALUES ('Namibie');
INSERT INTO Pays (libelle_pays) VALUES ('Nauru');
INSERT INTO Pays (libelle_pays) VALUES ('Népal');
INSERT INTO Pays (libelle_pays) VALUES ('Nicaragua');
INSERT INTO Pays (libelle_pays) VALUES ('Niger');
INSERT INTO Pays (libelle_pays) VALUES ('Nigeria');
INSERT INTO Pays (libelle_pays) VALUES ('Norvège');
INSERT INTO Pays (libelle_pays) VALUES ('Nouvelle-Zélande');
INSERT INTO Pays (libelle_pays) VALUES ('Oman');
INSERT INTO Pays (libelle_pays) VALUES ('Ouganda');
INSERT INTO Pays (libelle_pays) VALUES ('Ouzbékistan');
INSERT INTO Pays (libelle_pays) VALUES ('Pakistan');
INSERT INTO Pays (libelle_pays) VALUES ('Palaos');
INSERT INTO Pays (libelle_pays) VALUES ('Palestine');
INSERT INTO Pays (libelle_pays) VALUES ('Panama');
INSERT INTO Pays (libelle_pays) VALUES ('Papouasie-Nouvelle-Guinée');
INSERT INTO Pays (libelle_pays) VALUES ('Paraguay');
INSERT INTO Pays (libelle_pays) VALUES ('Pays-Bas');
INSERT INTO Pays (libelle_pays) VALUES ('Pérou');
INSERT INTO Pays (libelle_pays) VALUES ('Philippines');
INSERT INTO Pays (libelle_pays) VALUES ('Pologne');
INSERT INTO Pays (libelle_pays) VALUES ('Portugal');
INSERT INTO Pays (libelle_pays) VALUES ('Qatar');
INSERT INTO Pays (libelle_pays) VALUES ('République centrafricaine');
INSERT INTO Pays (libelle_pays) VALUES ('République démocratique du Congo');
INSERT INTO Pays (libelle_pays) VALUES ('République dominicaine');
INSERT INTO Pays (libelle_pays) VALUES ('République tchèque');
INSERT INTO Pays (libelle_pays) VALUES ('Roumanie');
INSERT INTO Pays (libelle_pays) VALUES ('Royaume-Uni');
INSERT INTO Pays (libelle_pays) VALUES ('Russie');
INSERT INTO Pays (libelle_pays) VALUES ('Rwanda');
INSERT INTO Pays (libelle_pays) VALUES ('Saint-Kitts-et-Nevis');
INSERT INTO Pays (libelle_pays) VALUES ('Saint-Marin');
INSERT INTO Pays (libelle_pays) VALUES ('Saint-Vincent-et-les-Grenadines');
INSERT INTO Pays (libelle_pays) VALUES ('Sainte-Lucie');
INSERT INTO Pays (libelle_pays) VALUES ('Salvador');
INSERT INTO Pays (libelle_pays) VALUES ('Samoa');
INSERT INTO Pays (libelle_pays) VALUES ('São Tomé-et-Principe');
INSERT INTO Pays (libelle_pays) VALUES ('Sénégal');
INSERT INTO Pays (libelle_pays) VALUES ('Serbie');
INSERT INTO Pays (libelle_pays) VALUES ('Seychelles');
INSERT INTO Pays (libelle_pays) VALUES ('Sierra Leone');
INSERT INTO Pays (libelle_pays) VALUES ('Singapour');
INSERT INTO Pays (libelle_pays) VALUES ('Slovaquie');
INSERT INTO Pays (libelle_pays) VALUES ('Slovénie');
INSERT INTO Pays (libelle_pays) VALUES ('Somalie');
INSERT INTO Pays (libelle_pays) VALUES ('Soudan');
INSERT INTO Pays (libelle_pays) VALUES ('Soudan du Sud');
INSERT INTO Pays (libelle_pays) VALUES ('Sri Lanka');
INSERT INTO Pays (libelle_pays) VALUES ('Suède');
INSERT INTO Pays (libelle_pays) VALUES ('Suisse');
INSERT INTO Pays (libelle_pays) VALUES ('Suriname');
INSERT INTO Pays (libelle_pays) VALUES ('Syrie');
INSERT INTO Pays (libelle_pays) VALUES ('Tadjikistan');
INSERT INTO Pays (libelle_pays) VALUES ('Tanzanie');
INSERT INTO Pays (libelle_pays) VALUES ('Tchad');
INSERT INTO Pays (libelle_pays) VALUES ('Thaïlande');
INSERT INTO Pays (libelle_pays) VALUES ('Timor oriental');
INSERT INTO Pays (libelle_pays) VALUES ('Togo');
INSERT INTO Pays (libelle_pays) VALUES ('Tonga');
INSERT INTO Pays (libelle_pays) VALUES ('Trinité-et-Tobago');
INSERT INTO Pays (libelle_pays) VALUES ('Tunisie');
INSERT INTO Pays (libelle_pays) VALUES ('Turkménistan');
INSERT INTO Pays (libelle_pays) VALUES ('Turquie');
INSERT INTO Pays (libelle_pays) VALUES ('Tuvalu');
INSERT INTO Pays (libelle_pays) VALUES ('Ukraine');
INSERT INTO Pays (libelle_pays) VALUES ('Uruguay');
INSERT INTO Pays (libelle_pays) VALUES ('Vanuatu');
INSERT INTO Pays (libelle_pays) VALUES ('Vatican');
INSERT INTO Pays (libelle_pays) VALUES ('Venezuela');
INSERT INTO Pays (libelle_pays) VALUES ('Viêt Nam');
INSERT INTO Pays (libelle_pays) VALUES ('Yémen');
INSERT INTO Pays (libelle_pays) VALUES ('Zambie');
INSERT INTO Pays (libelle_pays) VALUES ('Zimbabwe');